ruohan-consumer:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka, http://localhost:8672/eureka
      register-with-eureka: false
server:
  port: 8000
eureka:
  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
    register-with-eureka: false
#    fetch-registry: true
#ribbon:
#  eureka:
#    enabled: false
feign:
  hystrix:
    enabled: true
